# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Julien DAUPHANT
tagline:          Blog of Julien
description:      Personnal blog of Julien DAUPHANT @jdauphant
url:              http://julien.dauphant.com

author:
  name:           Julien DAUPHANT
  url:            https://twitter.com/jdauphant

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jdauphant/jdauphant.github.io
