# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Julien DAUPHANT
tagline:          Blog of Julien
description:      Personnal blog of Julien DAUPHANT @jdauphant
url:              http://julien.dauphant.com

author:
  name:           Julien DAUPHANT
  twitter:        https://twitter.com/jdauphant
  github:         https://github.com/jdauphant

paginate:         3

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/jdauphant/jdauphant.github.io
