# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Julien DAUPHANT
tagline:          
description:      Personnal page of Julien DAUPHANT @jdauphant
url:              http://julien.dauphant.com

author:
  name:           Julien DAUPHANT
  twitter:        https://twitter.com/jdauphant
  github:         https://github.com/jdauphant
  medium:	  https://medium.com/@jdauphant
  stackoverflow:  https://stackoverflow.com/users/1045832/julien-dauphant
  travis:         https://travis-ci.org/jdauphant

paginate:         3

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/jdauphant/jdauphant.github.io
